# Generated by Django 5.2 on 2025-04-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
