# Generated by Django 5.2 on 2025-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('cash', 'Cash at Pickup'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference number for payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
