# Generated by Django 5.2 on 2025-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_reservation_payment_date_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of booking', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_expiry',
            field=models.DateTimeField(blank=True, help_text='وقت انتهاء صلاحية التأكيد (24 ساعة)', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_details',
            field=models.TextField(blank=True, help_text='Additional details about the guarantee', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_type',
            field=models.CharField(blank=True, choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('deposit', 'Security Deposit'), ('credit_card', 'Credit Card Hold'), ('property_doc', 'Property Document')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_card_image',
            field=models.ImageField(blank=True, help_text='Photo of national ID card', null=True, upload_to='customer_ids/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily Rental'), ('weekly', 'Weekly Rental'), ('monthly', 'Monthly Rental'), ('corporate', 'Corporate Rental'), ('special', 'Special Event')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('cash', 'Cash at Pickup'), ('bank_transfer', 'Bank Transfer'), ('electronic', 'Electronic Payment')], max_length=20, null=True),
        ),
    ]
