# Generated by Django 5.2 on 2025-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_favoritecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
