# Generated by Django 5.2 on 2025-04-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_car_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة للإيجار'), ('maintenance', 'في الصيانة'), ('reserved', 'محجوزة')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
