# Generated by Django 5.2 on 2025-04-21 00:51

import django.db.models.deletion
import django.utils.timezone
import rental.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_car_status_alter_reservation_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='كاررنتال', max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, null=True, verbose_name='وصف الموقع')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='شعار الموقع')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='أيقونة الموقع')),
                ('site_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('site_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('site_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='رابط انستجرام')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='رابط تيك توك')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API لخرائط جوجل')),
                ('payment_gateway_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API لبوابة الدفع')),
                ('booking_start_time', models.TimeField(default='09:00', verbose_name='وقت بدء الحجز')),
                ('booking_end_time', models.TimeField(default='18:00', verbose_name='وقت انتهاء الحجز')),
                ('min_booking_days', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى لأيام الحجز')),
                ('max_booking_days', models.PositiveIntegerField(default=30, verbose_name='الحد الأقصى لأيام الحجز')),
                ('primary_color', models.CharField(default='#3a86ff', max_length=20, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#334155', max_length=20, verbose_name='اللون الثانوي')),
                ('enable_dark_mode', models.BooleanField(default=True, verbose_name='تفعيل الوضع المظلم')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('document_type', models.CharField(choices=[('contract', 'عقد'), ('receipt', 'إيصال'), ('custody', 'عهدة'), ('custody_release', 'إخلاء عهدة'), ('official_document', 'وثيقة رسمية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المستند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المستند')),
                ('file', models.FileField(upload_to=rental.models.archive_document_path, verbose_name='ملف المستند')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, verbose_name='حجم الملف (بايت)')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المستند')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('related_to', models.CharField(choices=[('reservation', 'حجز'), ('car', 'سيارة'), ('user', 'مستخدم'), ('employee', 'موظف'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='متعلق بـ')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المرجعي')),
                ('is_archived', models.BooleanField(default=True, verbose_name='مؤرشف')),
                ('tags', models.CharField(blank=True, help_text='فصل بفواصل', max_length=255, null=True, verbose_name='الكلمات المفتاحية')),
                ('enable_two_factor_auth', models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية')),
                ('booking_confirmation_expiry_hours', models.PositiveIntegerField(default=24, verbose_name='ساعات انتهاء صلاحية تأكيد الحجز')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة انتهاء الجلسة بالدقائق')),
                ('enable_deposit', models.BooleanField(default=True, verbose_name='تفعيل نظام العربون')),
                ('deposit_percentage', models.PositiveIntegerField(default=20, verbose_name='نسبة العربون من إجمالي الحجز (%)')),
                ('enable_automatic_reservation_expiry', models.BooleanField(default=True, verbose_name='تفعيل انتهاء صلاحية الحجز التلقائي')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('enable_debug_mode', models.BooleanField(default=False, verbose_name='تفعيل وضع التصحيح')),
                ('cache_timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة انتهاء ذاكرة التخزين المؤقت بالدقائق')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات بالبريد الإلكتروني')),
                ('enable_sms_notifications', models.BooleanField(default=False, verbose_name='تفعيل الإشعارات بالرسائل النصية')),
                ('admin_notification_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني لإشعارات المدير')),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة الافتراضية')),
                ('default_timezone', models.CharField(default='Asia/Kuwait', max_length=100, verbose_name='المنطقة الزمنية الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_documents', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='rental.car', verbose_name='السيارة المرتبطة')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='rental.reservation', verbose_name='الحجز المرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
