# Generated by Django 5.2 on 2025-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_archivefolder_document_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'وثيقة مؤرشفة', 'verbose_name_plural': 'الوثائق المؤرشفة'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='admin_notification_email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='booking_confirmation_expiry_hours',
        ),
        migrations.RemoveField(
            model_name='document',
            name='cache_timeout_minutes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='default_timezone',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deposit_percentage',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_automatic_reservation_expiry',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_debug_mode',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_deposit',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_email_notifications',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_sms_notifications',
        ),
        migrations.RemoveField(
            model_name='document',
            name='enable_two_factor_auth',
        ),
        migrations.RemoveField(
            model_name='document',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='document',
            name='session_timeout_minutes',
        ),
        migrations.AddField(
            model_name='document',
            name='is_auto_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
    ]
