# Generated by Django 5.2 on 2025-04-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_alter_document_options_and_more'),
        ('rental', '0013_add_file_content_fields'),
    ]

    operations = [
    ]
