# Generated by Django 5.2 on 2025-04-26 01:34
"""
هذه الحقول تم إضافتها بالفعل في الهجرة 0013_add_document_file_content_fields
لذلك نتجاهل إنشائها مرة أخرى لتفادي خطأ تكرار الأعمدة في قاعدة البيانات
"""

import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_add_document_file_content_fields'),
    ]

    # تم حذف العمليات لأن الحقول موجودة بالفعل في قاعدة البيانات
    operations = [
    ]
