# Generated by Django 5.2 on 2025-04-26 22:24

import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_document_file_content_document_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='محتوى الملف'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الملف الأصلي'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=rental.models.archive_document_path, verbose_name='ملف المستند'),
        ),
    ]
