# Generated by Django 5.2 on 2025-04-30 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_document_file_content_document_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('delivery', 'تسليم للعميل'), ('return', 'استلام من العميل'), ('maintenance', 'فحص صيانة'), ('periodic', 'فحص دوري')], max_length=20, verbose_name='نوع التقرير')),
                ('mileage', models.PositiveIntegerField(verbose_name='المسافة المقطوعة (كم)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقرير')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
                ('defects', models.TextField(blank=True, null=True, verbose_name='الأعطال')),
                ('defect_cause', models.TextField(blank=True, null=True, verbose_name='سبب العطل')),
                ('car_condition', models.CharField(choices=[('excellent', 'ممتازة'), ('good', 'جيدة'), ('fair', 'متوسطة'), ('poor', 'سيئة'), ('damaged', 'متضررة')], max_length=20, verbose_name='حالة السيارة العامة')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الإصلاح')),
                ('fuel_level', models.CharField(choices=[('empty', 'فارغ'), ('quarter', 'ربع'), ('half', 'نصف'), ('three_quarters', 'ثلاثة أرباع'), ('full', 'ممتلئ')], max_length=20, verbose_name='مستوى الوقود')),
                ('maintenance_type', models.CharField(blank=True, choices=[('regular', 'صيانة دورية'), ('repair', 'إصلاح عطل'), ('inspection', 'فحص فني'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع الصيانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='rental.car', verbose_name='السيارة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_condition_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم التوثيق بواسطة')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='rental.reservation', verbose_name='الحجز المرتبط')),
            ],
            options={
                'verbose_name': 'تقرير حالة السيارة',
                'verbose_name_plural': 'تقارير حالة السيارات',
                'ordering': ['-date'],
            },
        ),
    ]
