# Generated by Django 5.2 on 2025-04-30 17:14

import django.db.models.deletion
import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_carconditionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفئة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة فحص السيارة',
                'verbose_name_plural': 'فئات فحص السيارة',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarInspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('excellent', 'ممتازة'), ('good', 'جيدة'), ('fair', 'متوسطة'), ('poor', 'سيئة'), ('damaged', 'متضررة'), ('not_applicable', 'غير منطبق')], max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_details', to='rental.carconditionreport', verbose_name='تقرير الحالة')),
            ],
            options={
                'verbose_name': 'تفاصيل فحص العنصر',
                'verbose_name_plural': 'تفاصيل فحص العناصر',
            },
        ),
        migrations.CreateModel(
            name='CarInspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rental.models.CarInspectionImage.inspection_image_path, verbose_name='الصورة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('inspection_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.carinspectiondetail', verbose_name='تفاصيل الفحص')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.carconditionreport', verbose_name='تقرير الحالة')),
            ],
            options={
                'verbose_name': 'صورة فحص السيارة',
                'verbose_name_plural': 'صور فحص السيارة',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CarInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العنصر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف العنصر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='rental.carinspectioncategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'عنصر فحص السيارة',
                'verbose_name_plural': 'عناصر فحص السيارة',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='inspection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rental.carinspectionitem', verbose_name='عنصر الفحص'),
        ),
        migrations.AlterUniqueTogether(
            name='carinspectiondetail',
            unique_together={('report', 'inspection_item')},
        ),
        migrations.CreateModel(
            name='CustomerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to=rental.models.CustomerSignature.signature_path, verbose_name='التوقيع')),
                ('is_customer', models.BooleanField(default=True, verbose_name='توقيع العميل')),
                ('signed_by_name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('signed_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوقيع')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='rental.carconditionreport', verbose_name='تقرير الحالة')),
            ],
            options={
                'verbose_name': 'توقيع على تقرير الحالة',
                'verbose_name_plural': 'توقيعات على تقارير الحالة',
                'unique_together': {('report', 'is_customer')},
            },
        ),
    ]
