# Generated by Django 5.2 on 2025-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_carinspectioncategory_carinspectiondetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinspectiondetail',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة اليد العاملة'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='needs_repair',
            field=models.BooleanField(default=False, verbose_name='يحتاج إصلاح'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الإصلاح'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإصلاح'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الإصلاح المطلوب'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_parts',
            field=models.TextField(blank=True, null=True, verbose_name='قطع الغيار المطلوبة'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_status',
            field=models.CharField(choices=[('not_needed', 'لا يحتاج إصلاح'), ('needed', 'يحتاج إصلاح'), ('in_progress', 'قيد الإصلاح'), ('completed', 'تم الإصلاح')], default='not_needed', max_length=20, verbose_name='حالة الإصلاح'),
        ),
        migrations.AddField(
            model_name='carinspectiondetail',
            name='repair_workshop',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الورشة المسؤولة عن الإصلاح'),
        ),
    ]
