# Generated by Django 5.2 on 2025-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_carconditionreport_inspection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carconditionreport',
            name='electronic_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='car_reports/electronic_reports/', verbose_name='ملف تقرير الفحص الإلكتروني'),
        ),
        migrations.AddField(
            model_name='carconditionreport',
            name='is_electronic_inspection',
            field=models.BooleanField(default=False, verbose_name='فحص إلكتروني'),
        ),
    ]
