# Generated by Django 5.2 on 2025-05-05 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_customerguarantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصلاحية')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='رمز الصلاحية')),
                ('description', models.TextField(verbose_name='وصف الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='مسؤول أعلى')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP للدخول')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز الوصول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مسؤول',
                'verbose_name_plural': 'المسؤولين',
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rental.adminuser', verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'نشاط المسؤول',
                'verbose_name_plural': 'أنشطة المسؤولين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField(verbose_name='معرف التقييم الأصلي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('flagged', 'تم تمييزه')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المسؤول')),
                ('action_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإجراء')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_reviews', to='rental.adminuser', verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'إدارة تقييم',
                'verbose_name_plural': 'إدارة التقييمات',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('permissions', models.ManyToManyField(to='rental.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.role', verbose_name='الدور'),
        ),
    ]
