# Generated by Django 5.2 on 2025-05-06 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_permission_adminuser_adminactivity_reviewmanagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, null=True, verbose_name='القيمة')),
                ('value_type', models.CharField(choices=[('string', 'نص'), ('integer', 'رقم صحيح'), ('float', 'رقم عشري'), ('boolean', 'منطقي'), ('json', 'JSON'), ('list', 'قائمة')], default='string', max_length=20, verbose_name='نوع القيمة')),
                ('group', models.CharField(choices=[('general', 'إعدادات عامة'), ('security', 'الأمان'), ('notifications', 'الإشعارات'), ('backup', 'النسخ الاحتياطي'), ('email', 'البريد الإلكتروني'), ('business', 'بيانات الأعمال'), ('appearance', 'المظهر'), ('other', 'أخرى')], default='general', max_length=20, verbose_name='المجموعة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('job_type', models.CharField(choices=[('backup', 'نسخ احتياطي'), ('cleanup', 'تنظيف'), ('report', 'تقرير'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع المهمة')),
                ('function_name', models.CharField(max_length=100, verbose_name='اسم الدالة')),
                ('args', models.JSONField(blank=True, default=dict, verbose_name='معاملات')),
                ('interval_type', models.CharField(choices=[('hourly', 'ساعي'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('custom', 'مخصص')], default='daily', max_length=20, verbose_name='نوع الفاصل الزمني')),
                ('interval_value', models.IntegerField(default=1, verbose_name='قيمة الفاصل الزمني')),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True, verbose_name='تعبير Cron')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('next_run', models.DateTimeField(verbose_name='التشغيل التالي')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('last_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='آخر حالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة مجدولة',
                'verbose_name_plural': 'المهام المجدولة',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('file_path', models.CharField(max_length=255, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('restored', 'تمت الاستعادة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('area', models.CharField(max_length=50, verbose_name='المنطقة')),
                ('severity', models.CharField(choices=[('critical', 'حرجة'), ('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المعالجة'), ('fixed', 'تم الإصلاح')], default='new', max_length=20, verbose_name='الحالة')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإصلاح')),
                ('fix_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإصلاح')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='تتبع المكدس')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإصلاح بواسطة')),
            ],
            options={
                'verbose_name': 'مشكلة النظام',
                'verbose_name_plural': 'مشاكل النظام',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ')], default='info', max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_system_wide', models.BooleanField(default=False, verbose_name='على مستوى النظام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الكائن المرتبط')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار النظام',
                'verbose_name_plural': 'إشعارات النظام',
                'ordering': ['-created_at'],
            },
        ),
    ]
