# Generated by Django 5.2 on 2025-05-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_loginattempt_twofactorsession_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='current_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوظيفة الحالية'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤهل'),
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to='rental.adminuser')),
            ],
        ),
    ]
