# Generated by Django 5.2 on 2025-05-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_loginattempt_twofactorsession_usersecurity'),
    ]

    operations = [
        # Removed all duplicate operations from this migration
        # All fields and models already exist in the database:
        # 1. AdminUser fields: current_job, department, full_name, phone_number, qualification
        # 2. AdminPermission model already exists
    ]
