# Generated by Django 5.2 on 2025-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_merge_20250509_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinspectionitem',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='حرج'),
        ),
        migrations.AddField(
            model_name='carinspectionitem',
            name='is_expensive',
            field=models.BooleanField(default=False, verbose_name='مكلف'),
        ),
        migrations.AddField(
            model_name='carinspectionitem',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='مهم'),
        ),
    ]
