# Generated by Django 5.2 on 2025-05-15 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_merge_backup_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivity',
            name='affected_item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف العنصر المتأثر'),
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='affected_item_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العنصر المتأثر'),
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='مخفي'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='current_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوظيفة الحالية'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف (مخفي)'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤهل'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to='rental.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحقق بريد إلكتروني',
                'verbose_name_plural': 'تحققات البريد الإلكتروني',
            },
        ),
    ]
