# Generated by Django 5.2 on 2025-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0031_adminuser_is_deleted_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerguarantee',
            name='credit_card_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معلومات البطاقة الائتمانية'),
        ),
        migrations.AddField(
            model_name='customerguarantee',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم بوليصة التأمين'),
        ),
        migrations.AddField(
            model_name='customerguarantee',
            name='property_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الممتلكات العقارية'),
        ),
    ]
