"""
قائمة الدول العالمية بالعربية والإنجليزية
"""

COUNTRIES = [
    ('AF', 'أفغانستان - Afghanistan'),
    ('AL', 'ألبانيا - Albania'),
    ('DZ', 'الجزائر - Algeria'),
    ('AS', 'ساموا الأمريكية - American Samoa'),
    ('AD', 'أندورا - Andorra'),
    ('AO', 'أنغولا - Angola'),
    ('AI', 'أنغويلا - Anguilla'),
    ('AQ', 'أنتاركتيكا - Antarctica'),
    ('AG', 'أنتيغوا وبربودا - Antigua and Barbuda'),
    ('AR', 'الأرجنتين - Argentina'),
    ('AM', 'أرمينيا - Armenia'),
    ('AW', 'أروبا - Aruba'),
    ('AU', 'أستراليا - Australia'),
    ('AT', 'النمسا - Austria'),
    ('AZ', 'أذربيجان - Azerbaijan'),
    ('BS', 'جزر البهاما - Bahamas'),
    ('BH', 'البحرين - Bahrain'),
    ('BD', 'بنغلاديش - Bangladesh'),
    ('BB', 'بربادوس - Barbados'),
    ('BY', 'بيلاروسيا - Belarus'),
    ('BE', 'بلجيكا - Belgium'),
    ('BZ', 'بليز - Belize'),
    ('BJ', 'بنين - Benin'),
    ('BM', 'برمودا - Bermuda'),
    ('BT', 'بوتان - Bhutan'),
    ('BO', 'بوليفيا - Bolivia'),
    ('BA', 'البوسنة والهرسك - Bosnia and Herzegovina'),
    ('BW', 'بوتسوانا - Botswana'),
    ('BV', 'جزيرة بوفيت - Bouvet Island'),
    ('BR', 'البرازيل - Brazil'),
    ('IO', 'إقليم المحيط البريطاني الهندي - British Indian Ocean Territory'),
    ('BN', 'بروناي - Brunei Darussalam'),
    ('BG', 'بلغاريا - Bulgaria'),
    ('BF', 'بوركينا فاسو - Burkina Faso'),
    ('BI', 'بوروندي - Burundi'),
    ('KH', 'كمبوديا - Cambodia'),
    ('CM', 'الكاميرون - Cameroon'),
    ('CA', 'كندا - Canada'),
    ('CV', 'الرأس الأخضر - Cape Verde'),
    ('KY', 'جزر كايمان - Cayman Islands'),
    ('CF', 'جمهورية أفريقيا الوسطى - Central African Republic'),
    ('TD', 'تشاد - Chad'),
    ('CL', 'تشيلي - Chile'),
    ('CN', 'الصين - China'),
    ('CX', 'جزيرة كريسماس - Christmas Island'),
    ('CC', 'جزر كوكوس - Cocos (Keeling) Islands'),
    ('CO', 'كولومبيا - Colombia'),
    ('KM', 'جزر القمر - Comoros'),
    ('CG', 'الكونغو - Congo'),
    ('CD', 'جمهورية الكونغو الديمقراطية - Democratic Republic of the Congo'),
    ('CK', 'جزر كوك - Cook Islands'),
    ('CR', 'كوستاريكا - Costa Rica'),
    ('CI', 'ساحل العاج - Côte d\'Ivoire'),
    ('HR', 'كرواتيا - Croatia'),
    ('CU', 'كوبا - Cuba'),
    ('CY', 'قبرص - Cyprus'),
    ('CZ', 'جمهورية التشيك - Czech Republic'),
    ('DK', 'الدنمارك - Denmark'),
    ('DJ', 'جيبوتي - Djibouti'),
    ('DM', 'دومينيكا - Dominica'),
    ('DO', 'جمهورية الدومينيكان - Dominican Republic'),
    ('EC', 'الإكوادور - Ecuador'),
    ('EG', 'مصر - Egypt'),
    ('SV', 'السلفادور - El Salvador'),
    ('GQ', 'غينيا الاستوائية - Equatorial Guinea'),
    ('ER', 'إريتريا - Eritrea'),
    ('EE', 'إستونيا - Estonia'),
    ('ET', 'إثيوبيا - Ethiopia'),
    ('FK', 'جزر فوكلاند - Falkland Islands'),
    ('FO', 'جزر فارو - Faroe Islands'),
    ('FJ', 'فيجي - Fiji'),
    ('FI', 'فنلندا - Finland'),
    ('FR', 'فرنسا - France'),
    ('GF', 'غيانا الفرنسية - French Guiana'),
    ('PF', 'بولينيزيا الفرنسية - French Polynesia'),
    ('TF', 'المناطق الفرنسية الجنوبية - French Southern Territories'),
    ('GA', 'الغابون - Gabon'),
    ('GM', 'غامبيا - Gambia'),
    ('GE', 'جورجيا - Georgia'),
    ('DE', 'ألمانيا - Germany'),
    ('GH', 'غانا - Ghana'),
    ('GI', 'جبل طارق - Gibraltar'),
    ('GR', 'اليونان - Greece'),
    ('GL', 'غرينلاند - Greenland'),
    ('GD', 'غرينادا - Grenada'),
    ('GP', 'غوادلوب - Guadeloupe'),
    ('GU', 'غوام - Guam'),
    ('GT', 'غواتيمالا - Guatemala'),
    ('GN', 'غينيا - Guinea'),
    ('GW', 'غينيا بيساو - Guinea-Bissau'),
    ('GY', 'غيانا - Guyana'),
    ('HT', 'هايتي - Haiti'),
    ('HM', 'جزيرة هيرد وجزر ماكدونالد - Heard Island and McDonald Islands'),
    ('VA', 'الفاتيكان - Holy See'),
    ('HN', 'هندوراس - Honduras'),
    ('HK', 'هونغ كونغ - Hong Kong'),
    ('HU', 'المجر - Hungary'),
    ('IS', 'آيسلندا - Iceland'),
    ('IN', 'الهند - India'),
    ('ID', 'إندونيسيا - Indonesia'),
    ('IR', 'إيران - Iran'),
    ('IQ', 'العراق - Iraq'),
    ('IE', 'أيرلندا - Ireland'),
    ('IL', 'إسرائيل - Israel'),
    ('IT', 'إيطاليا - Italy'),
    ('JM', 'جامايكا - Jamaica'),
    ('JP', 'اليابان - Japan'),
    ('JO', 'الأردن - Jordan'),
    ('KZ', 'كازاخستان - Kazakhstan'),
    ('KE', 'كينيا - Kenya'),
    ('KI', 'كيريباتي - Kiribati'),
    ('KP', 'كوريا الشمالية - North Korea'),
    ('KR', 'كوريا الجنوبية - South Korea'),
    ('KW', 'الكويت - Kuwait'),
    ('KG', 'قيرغيزستان - Kyrgyzstan'),
    ('LA', 'لاوس - Lao'),
    ('LV', 'لاتفيا - Latvia'),
    ('LB', 'لبنان - Lebanon'),
    ('LS', 'ليسوتو - Lesotho'),
    ('LR', 'ليبيريا - Liberia'),
    ('LY', 'ليبيا - Libya'),
    ('LI', 'ليختنشتاين - Liechtenstein'),
    ('LT', 'ليتوانيا - Lithuania'),
    ('LU', 'لوكسمبورغ - Luxembourg'),
    ('MO', 'ماكاو - Macao'),
    ('MK', 'مقدونيا الشمالية - North Macedonia'),
    ('MG', 'مدغشقر - Madagascar'),
    ('MW', 'ملاوي - Malawi'),
    ('MY', 'ماليزيا - Malaysia'),
    ('MV', 'جزر المالديف - Maldives'),
    ('ML', 'مالي - Mali'),
    ('MT', 'مالطا - Malta'),
    ('MH', 'جزر مارشال - Marshall Islands'),
    ('MQ', 'مارتينيك - Martinique'),
    ('MR', 'موريتانيا - Mauritania'),
    ('MU', 'موريشيوس - Mauritius'),
    ('YT', 'مايوت - Mayotte'),
    ('MX', 'المكسيك - Mexico'),
    ('FM', 'ميكرونيزيا - Micronesia'),
    ('MD', 'مولدوفا - Moldova'),
    ('MC', 'موناكو - Monaco'),
    ('MN', 'منغوليا - Mongolia'),
    ('MS', 'مونتسيرات - Montserrat'),
    ('MA', 'المغرب - Morocco'),
    ('MZ', 'موزمبيق - Mozambique'),
    ('MM', 'ميانمار - Myanmar'),
    ('NA', 'ناميبيا - Namibia'),
    ('NR', 'ناورو - Nauru'),
    ('NP', 'نيبال - Nepal'),
    ('NL', 'هولندا - Netherlands'),
    ('NC', 'كاليدونيا الجديدة - New Caledonia'),
    ('NZ', 'نيوزيلندا - New Zealand'),
    ('NI', 'نيكاراغوا - Nicaragua'),
    ('NE', 'النيجر - Niger'),
    ('NG', 'نيجيريا - Nigeria'),
    ('NU', 'نيوي - Niue'),
    ('NF', 'جزيرة نورفولك - Norfolk Island'),
    ('MP', 'جزر ماريانا الشمالية - Northern Mariana Islands'),
    ('NO', 'النرويج - Norway'),
    ('OM', 'عمان - Oman'),
    ('PK', 'باكستان - Pakistan'),
    ('PW', 'بالاو - Palau'),
    ('PS', 'فلسطين - Palestine'),
    ('PA', 'بنما - Panama'),
    ('PG', 'بابوا غينيا الجديدة - Papua New Guinea'),
    ('PY', 'باراغواي - Paraguay'),
    ('PE', 'بيرو - Peru'),
    ('PH', 'الفلبين - Philippines'),
    ('PN', 'جزر بيتكيرن - Pitcairn'),
    ('PL', 'بولندا - Poland'),
    ('PT', 'البرتغال - Portugal'),
    ('PR', 'بورتوريكو - Puerto Rico'),
    ('QA', 'قطر - Qatar'),
    ('RE', 'ريونيون - Réunion'),
    ('RO', 'رومانيا - Romania'),
    ('RU', 'روسيا - Russia'),
    ('RW', 'رواندا - Rwanda'),
    ('SH', 'سانت هيلينا - Saint Helena'),
    ('KN', 'سانت كيتس ونيفيس - Saint Kitts and Nevis'),
    ('LC', 'سانت لوسيا - Saint Lucia'),
    ('PM', 'سان بيير وميكلون - Saint Pierre and Miquelon'),
    ('VC', 'سانت فنسنت وجزر غرينادين - Saint Vincent and the Grenadines'),
    ('WS', 'ساموا - Samoa'),
    ('SM', 'سان مارينو - San Marino'),
    ('ST', 'ساو تومي وبرينسيبي - Sao Tome and Principe'),
    ('SA', 'المملكة العربية السعودية - Saudi Arabia'),
    ('SN', 'السنغال - Senegal'),
    ('SC', 'سيشل - Seychelles'),
    ('SL', 'سيراليون - Sierra Leone'),
    ('SG', 'سنغافورة - Singapore'),
    ('SK', 'سلوفاكيا - Slovakia'),
    ('SI', 'سلوفينيا - Slovenia'),
    ('SB', 'جزر سليمان - Solomon Islands'),
    ('SO', 'الصومال - Somalia'),
    ('ZA', 'جنوب أفريقيا - South Africa'),
    ('GS', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية - South Georgia and the South Sandwich Islands'),
    ('ES', 'إسبانيا - Spain'),
    ('LK', 'سريلانكا - Sri Lanka'),
    ('SD', 'السودان - Sudan'),
    ('SS', 'جنوب السودان - South Sudan'),
    ('SR', 'سورينام - Suriname'),
    ('SJ', 'سفالبارد وجان ماين - Svalbard and Jan Mayen'),
    ('SZ', 'إسواتيني - Eswatini'),
    ('SE', 'السويد - Sweden'),
    ('CH', 'سويسرا - Switzerland'),
    ('SY', 'سوريا - Syria'),
    ('TW', 'تايوان - Taiwan'),
    ('TJ', 'طاجيكستان - Tajikistan'),
    ('TZ', 'تنزانيا - Tanzania'),
    ('TH', 'تايلاند - Thailand'),
    ('TL', 'تيمور الشرقية - Timor-Leste'),
    ('TG', 'توغو - Togo'),
    ('TK', 'توكيلاو - Tokelau'),
    ('TO', 'تونغا - Tonga'),
    ('TT', 'ترينيداد وتوباغو - Trinidad and Tobago'),
    ('TN', 'تونس - Tunisia'),
    ('TR', 'تركيا - Turkey'),
    ('TM', 'تركمانستان - Turkmenistan'),
    ('TC', 'جزر تركس وكايكوس - Turks and Caicos Islands'),
    ('TV', 'توفالو - Tuvalu'),
    ('UG', 'أوغندا - Uganda'),
    ('UA', 'أوكرانيا - Ukraine'),
    ('AE', 'الإمارات العربية المتحدة - United Arab Emirates'),
    ('GB', 'المملكة المتحدة - United Kingdom'),
    ('US', 'الولايات المتحدة الأمريكية - United States'),
    ('UM', 'جزر الولايات المتحدة البعيدة الصغيرة - United States Minor Outlying Islands'),
    ('UY', 'أوروغواي - Uruguay'),
    ('UZ', 'أوزبكستان - Uzbekistan'),
    ('VU', 'فانواتو - Vanuatu'),
    ('VE', 'فنزويلا - Venezuela'),
    ('VN', 'فيتنام - Vietnam'),
    ('VG', 'جزر فيرجن البريطانية - British Virgin Islands'),
    ('VI', 'جزر فيرجن الأمريكية - U.S. Virgin Islands'),
    ('WF', 'واليس وفوتونا - Wallis and Futuna'),
    ('EH', 'الصحراء الغربية - Western Sahara'),
    ('YE', 'اليمن - Yemen'),
    ('ZM', 'زامبيا - Zambia'),
    ('ZW', 'زيمبابوي - Zimbabwe'),
]